### ISSUE TITLE
Trouble with embedded RTcmix

### ISSUE THREAD

**Issue by eval-apply** [RTcmix/RTcmix#11]
This might be less of an issue and more me missing something important, but I'm a bit confused by the embedded API's present.  On OSX built using STANDALONE target I've got code (in another language using WIP bindings) that is making the following calls:

`RTcmix *ctx = new RTcmix();`
`ctx->printOn();`
`ctx->cmd("load", 1, "WAVETABLE");`
`ctx->cmd("WAVETABLE", 0, 3.4, 5000.0, 278.0);`

Should that be sufficient to get audio going?  The way I read the example code was that using this API the RTcmix instance would handle the Audio I/O (unlike the EMBEDDED target for max externals etc).  The RTcmix instance is printing messages but none appear to be errors:

`--------> RTcmix 4.2.1 <--------`
`============================`
`load:  1.40735e+14 `
`load:  Loaded RT functions from shared library:`
`	'/usr/local/src/RTcmix/shlib/libWAVETABLE.so'.`
`========<rt-queueing>=======`
`WAVETABLE:  `
`No bus_config defined, setting default (in/out).`
`default: () => WAVETABLE => (out 0-1)`
`   `
`WAVETABLE:  No wavetable specified, so using sine wave.`

**Comment by dougscott** [comment]
Does your code which calls the above functions sleep after that?  How do you keep it from simply exiting?  You will only be able to generate audio while your process is running.

**Comment by eval-apply** [comment]
The calls were made from a long running process (a interactive repl).

**Comment by dougscott** [comment]
Instead of printOn(), call cmd("print_on", 1, 6).  See if you get any
logging that gives us a clue.

**Comment by dougscott** [comment]
Please update this issue if there is still a problem, or I will close it to clean up.  Thanks.
