### ISSUE TITLE
s_arg() returns a float

### ISSUE THREAD

**Issue by rev3rend** [RTcmix/RTcmix#17]
s_arg() seems to return a float:

the following code, saved to 'foo.sco'...

```
print(s_arg(0))
f1 = type(s_arg(0))
print(f1) 

```
...run with...

`CMIX "hi there" < foo.sco`

...returns...

```
--------> RTcmix 4.3.1 (CMIX) <--------
============================
s_arg:  0 
1.40495986658e+14
============================
s_arg:  0 
"float"
```

for whatever reason, it still works with things like rtinput(), but not when using a filename argument in maketable().

/luke

**Comment by dougscott** [comment]
Yep, that's correct.

-Doug

**Comment by rev3rend** [comment]
ah that's super useful. i'll try that. thanks!
