### ISSUE TITLE
compiling version 4.3.1

### ISSUE THREAD

**Issue by rev3rend** [RTcmix/RTcmix#18]
I get this build error building on MacOS Mojave (10.14.5) using xcode 10.2.1's command line tools:

```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/lukedubois/RTcmix-4.3.1/src/control/mouse/MouseWindow/build/Release/MouseWindow.app/Contents/MacOS/MouseWindow normal x86_64
(1 failure)
make: *** [MouseWindow] Error 65
```

not sure what makefile to tweak to get it to make it through.

**Comment by johgibso** [comment]
Hi Luke,

I'm getting this too on Mojave. Let me see if there's a quick fix.

John

**Comment by johgibso** [comment]
Luke, for now, I would simply edit src/control/mouse/Makefile to keep it from running the xcodebuild line. Same for DisplayWindow in src/control/display/Makefile. RTcmix doesn't need either of these GUIs. I suspect the project file is woefully out of date.

It's a shame this halts the entire build.

John

**Comment by johgibso** [comment]
Also, I would do a "make distclean" from the top level, and do another ./configure; make & make install.

When "make clean" hits these dirs, they may fail, depending on how you disabled xcodebuild in those Makefiles. It also calls xcodebuild for the clean. Disable that as well.

And don't run any code that wants the MouseWindow app!  :)

J

**Comment by rev3rend** [comment]
thanks, john. commenting out the xcodebuild lines works great. wonder if we should silo those projects.

**Comment by johgibso** [comment]
I think we should keep them, because they are occasionally useful. And I just fixed the problem with them. Will check that in soon. But you can leave your code as is if you never use these.

Thanks for uncovering this! I only just upgraded to Mojave a few weeks ago. :)

J

**Comment by rev3rend** [comment]
no sweat. glad it was an easy fix.

**Comment by johgibso** [comment]
Fixes are checked in. I should probably also drop the 32-bit build target so that we don't have to think about this in the fall.

**Comment by dougscott** [comment]
RTcmix is supposed to be configurable to use newer versions of the SDK for
these subprojects using macros at the top level.  I guess this is currently
not implemented/not working for the mouse subproject.

-Doug

**Comment by dougscott** [comment]
I got a completely different compile issue when I tried to build for Mojave:

c++ -Wno-deprecated  -I. -I/Users/dscott/project/RTcmix.git/include
-I../sndlib -I../rtcmix -I/Users/dscott/project/RTcmix.git/include -g3 -O3
-Wall -Wno-unused  -fno-common -DMACOSX    -m64 -DSTANDALONE
-DUSE_OSX_DISPATCH -DAPPLEAUDIO -DNETAUDIO -DMULTI_THREAD -DAPPLE -c
AppleAudioDevice.cpp -o AppleAudioDevice.o

In file included from AppleAudioDevice.cpp:14:

In file included from /Users/dscott/project/RTcmix.git/include/ugens.h:12:

*/Users/dscott/project/RTcmix.git/include/rt_types.h:24:3: **error: **expected
identifier*

  NO = 0,

*  ^*

*/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/include/objc/objc.h:90:13:
note: *expanded from macro 'NO'

#define NO  __objc_no

This is due to Clang's support for Objective C I suspect - even though this
file is pure C++.

I'll fix this by wrapping it in an #ifndef

-DS

**Comment by dougscott** [comment]
I think the fix should be done a different way.  The Makefiles in the
directories that do an Xcode build (maxmsp, for example) have lines like
this:

OSX_VERSION=`xcrun --show-sdk-version`

SDKROOT = macosx${OSX_VERSION}

MACOSX_DEPLOYMENT_TARGET = ${OSX_VERSION}

        xcodebuild -project rtcmix~.xcodeproj -target rtcmix~
-configuration ${TARGET} -arch i386 MAX_SDK_PATH=${MAX_SDK_PATH}
SDKROOT=${SDKROOT} MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET}

To fix the issues that were being reported, OSX_VERSION has to be set in
the top-level config files, and we need to change the above command from
"-arch i386" to "-arch ${OSX_ARCH}", and then define that macro right next
to OSX_VERSION.  This will allow people to build the system regardless of
whether they have Mojave or an earlier version of OSX.

I'm going to fix this right now.

-Doug

**Comment by johgibso** [comment]
Can you point me to the support you're talking about?
J

**Comment by johgibso** [comment]
How come I didn't get this?

I have Mojave 10.14.5, Apple LLVM version 10.0.1 (clang-1001.0.46.4)

**Comment by johgibso** [comment]
Oh, I see. (My last email crossed with this one from you.)

**Comment by dougscott** [comment]
Ah never mind - you did this with BUILD_ARCH - you just did not put your
changes into src/maxmsp/

-Doug

**Comment by johgibso** [comment]
No, all I did yesterday was update the xcode project file from 10.8 to 10.9 SDK.
I didn't know about the fancy macro stuff you quote below from the maxmsp dir.
If you think that's best, go for it.

John
