### ISSUE TITLE
Troubleshooting "Unrecognized output device name" in Standalone

### ISSUE THREAD

**Issue by ggorlen** [RTcmix/RTcmix#19]
_Apologies if this is off-topic (novice here). I couldn't locate any other help resource or community forum for RTcmix (if there is one, please point me to it!)._
 
Environment: Ubuntu 18.04.3 LTS.

I followed the installation guide and built the project without issue using the `--with-alsa` flag. However, when I attempted to run a demo .sco per the instructions:
```
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ CMIX < WAVY1.sco
--------> RTcmix 4.3.1 (CMIX) <--------
============================
rtsetparams:  44100 2 256 
Unrecognized output device name '(null)'.
*** FATAL ERROR [rtsetparams]:  Failed to create audio device.
```

No mention of configuring an audio device was in the documentation (this could be a possible addition if the problem is indeed general?).

Reading through the docs, I noticed I could use `set_option("device = devname")` to specify a valid device name (by the way, the link to http://www.alsa-project.org/alsa-doc/doc-php/asoundrc.php?module=Generic in http://rtcmix.org/reference/scorefile/set_option.php is broken). I ran a few commands per https://superuser.com/questions/626606/ and https://superuser.com/questions/53957/ to see my devices:

```
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: MID [HDA Intel MID], device 0: ALC269 Analog [ALC269 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: MID [HDA Intel MID], device 1: ALC269 Digital [ALC269 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: MID [HDA Intel MID], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 7: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 8: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 9: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ cat /proc/asound/cards
 0 [MID            ]: HDA-Intel - HDA Intel MID
                      HDA Intel MID at 0xeb000000 irq 40
 1 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xe3080000 irq 16
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ aplay -l | awk -F \: '/,/{print $2}' | awk '{print $1}' | uniq
MID
NVidia
```

Also,
```
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ aplay -D default test.wav
Playing WAVE 'test.wav' : Signed 16 bit Little Endian, Rate 96000 Hz, Stereo
```
works great.

I tried the following in `test.sco`:
```
set_option("device = NVidia")
rtsetparams(44100, 2)
load("WAVETABLE") 
waveform = maketable("wave", 1000, "tri") 
WAVETABLE(0, 3.5, 20000, 440.0, 0.5, waveform) 
```

Running this gives:
```
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ CMIX < test.sco
--------> RTcmix 4.3.1 (CMIX) <--------
============================
set_option:  "device = NVidia" 
============================
rtsetparams:  44100 2 
Unrecognized output device name 'NVidia'.
*** FATAL ERROR [rtsetparams]:  Failed to create audio device.
```

I also tried a number of other options for the device name: `hw:0,0`, `NVidia:0,0`, `front`, `default`, various combinations of numbers, etc, all to no avail.

How can I specify the correct alsa device name and get sound to emit from CMIX?

Thanks!

**Comment by johgibso** [comment]
Hi Greg,

I haven’t used Linux in a long time, but did you set your device to be “plughw”? That used to be what Alsa wanted.

There are two RTcmix mailing lists; the main one is 

https://lists.columbia.edu/mailman/listinfo/rtcmix-discuss

Be sure to visit rtcmix.org, if you haven't already.

John

**Comment by johgibso** [comment]
I see from your email you've already been to rtcmix.org. :)

To be specific about my suggestion, try

set_option(“device = plughw”)

When I used Linux, I moved away from Alsa directly to Jack. I don't know if our Jack code even works anymore, but that might be worth a shot.

There are a few people on the list who are far more Linux-savvy than I am.

John

**Comment by ggorlen** [comment]
Thanks for the response! I checked out the list but wasn't able to figure out how to make a post, so I came here. I tried `set_option("device = plughw")` but same Unrecognized output device name error. 

I also tried Jack: installed QJackCtl and ran it successfully but `--with-jack` wants a `jack` package too(?), so I'm not sure where I went wrong (`sudo apt-get install jack` seems unrelated?) probably beginner error here.

I tried `--with-perl` but `PCMIX < test2.pl` fails as above. 

Theoretically, how would Jack work around the device issue?

**Comment by johgibso** [comment]
Hi Greg,

You have to subscribe to the list before being able to post.

I don't have a Linux system anymore to check things out in detail, but you definitely need libjack and jack/jack.h in a place our build system can find. That is what the configure script is trying to determine. After running ./configure --with-jack, look at the resulting defs.conf in the top-level directory. What does it have for JACK_SUPPORT, JACK_CFLAGS, and JACK_LIBS? A true value for JACK_SUPPORT enables compilation of rtcmix/src/audio/JackAudioDevice.cpp. Please check for compilation errors when compiling in the audio directory.

If you don't have sensible values for JACK_LIBS, etc., it could be that your distro has a jack-dev package, as well as a jack package -- one that installs libs and headers, in addition to user programs.

If the defs.conf JACK* items look okay, the best thing is to do this from top level of rtcmix...

make uninstall
make distclean
./configure --with-jack
make >& errs.txt

and send the errs.txt file to me. If my colleague, Doug Scott, responds to your Github email, then he will want this file as well. Doug wrote the bulk of the rtcmix audio subsystem, though I confess to having written JackAudioDevice many moons ago.

As for the benefit of Jack, in addition to the interapplication patching functionality, I just found dealing with it much easier than thinking about the weird Also device specification syntax, which I never really could understand.

As for the Perl issue, it's a similar problem. Check defs.conf for PERL items, and see what errors you might get in rtcmix/src/parser.

And switch to Python, for goodness sake. :)

John

**Comment by ggorlen** [comment]
The Perl situation seems to be the same basic output device problem as with MINC, so the language doesn't appear to matter. Python wasn't building, so I skipped that in favor of Perl (I'll use whatever language I can get working).

For getting Jack headers, I think I needed `sudo apt-get install libjack-dev`, which worked. I then proceeded with the above instructions (plus `make install` to create the binaries) with no obvious complaints at any stage, but same result (`Unrecognized output device name '(null)'.`) when trying `CMIX < foo.sco`.

Log output:

[errs_configure_with_jack.txt](https://github.com/RTcmix/RTcmix/files/3512299/errs_configure_with_jack.txt)
[errs_make.txt](https://github.com/RTcmix/RTcmix/files/3512300/errs_make.txt)
[errs_make_install.txt](https://github.com/RTcmix/RTcmix/files/3512301/errs_make_install.txt)

**Comment by dougscott** [comment]
From that error, I think that the ALSA build configuration is not set up
correctly.

Greg, can you email us the output of the following:

cd src/audio
make clean
make -n

Thanks!

-Doug

**Comment by ggorlen** [comment]
Sure: [make_n.txt](https://github.com/RTcmix/RTcmix/files/3513743/make_n.txt). Thank you!

**Comment by dougscott** [comment]
Ah, I see you have it configured for Jack right now - could you reconfigure
for ALSA and resend that make output?  I know that interface way better.
Thanks.

-DS

**Comment by ggorlen** [comment]
Sure. Hope this helps: 
[configure_with_alsa.txt](https://github.com/RTcmix/RTcmix/files/3513837/configure_with_alsa.txt)
[make.txt](https://github.com/RTcmix/RTcmix/files/3513839/make.txt)
[make_install.txt](https://github.com/RTcmix/RTcmix/files/3513838/make_install.txt)
[make_clean.txt](https://github.com/RTcmix/RTcmix/files/3513841/make_clean.txt)
[make_n.txt](https://github.com/RTcmix/RTcmix/files/3513842/make_n.txt)

**Comment by dougscott** [comment]
Hm, the configuration looks ok.  You say that if your score has:

set_option("device = NVidia")

you get:


*Unrecognized output device name 'NVidia'.*

If you use:

set_option("device = plughw")

you get

*Unrecognized output device name 'plughw'*

Right?

Running out of ideas - the ALSA device code recognizes ANY output device
name the starts with "plug" or with "hw:".  If it failed to *open* those
devices, that would be one thing.  But having it not *recognize* the device
name at ALL tells me that something is wrong with the configuration, but I
cannot tell what.  Does the 'cmixplay' command play audio successfully?

-Doug

**Comment by ggorlen** [comment]
Correct, re: device name (everything in this post uses the same build as above):

```
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ CMIX < test.sco
--------> RTcmix 4.3.1 (CMIX) <--------
============================
set_option:  "device = plughw" 
============================
rtsetparams:  44100 2 
*** FATAL ERROR [rtsetparams]:  AudioDevice: Cannot open audio output device: No such file or directory
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ CMIX < test.sco
--------> RTcmix 4.3.1 (CMIX) <--------
============================
set_option:  "device = NVidia" 
============================
rtsetparams:  44100 2 
Unrecognized output device name 'NVidia'.
*** FATAL ERROR [rtsetparams]:  Failed to create audio device.
greg@greg-N61Jv:~/programming/RTcmix/docs/sample_scores$ CMIX < WIGGLE4.sco
--------> RTcmix 4.3.1 (CMIX) <--------
============================
rtsetparams:  44100 2 
*** FATAL ERROR [rtsetparams]:  AudioDevice: This format conversion is currently not supported!
```

No luck with cmixplay, unfortunately:

```
greg@greg-N61Jv:~/programming/RTcmix/bin$ aplay ../snd/nucular.wav
Playing WAVE '../snd/nucular.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono
greg@greg-N61Jv:~/programming/RTcmix/bin$ cmixplay ../snd/nucular.wav
AudioDevice: Cannot set channel count: Invalid argument
greg@greg-N61Jv:~/programming/RTcmix/bin$ cmixplay ../snd/stereotest.wav
AudioDevice: This format conversion is currently not supported!
greg@greg-N61Jv:~/programming/RTcmix/bin$ cmixplay ../docs/*sample_sc*/test.wav
AudioDevice: This format conversion is currently not supported!
greg@greg-N61Jv:~/programming/RTcmix/bin$ cmixplay ../snd/loocher.aiff
AudioDevice: Cannot set channel count: Invalid argument
```

**Comment by dougscott** [comment]
Actually, these errors all mean something different:

*** FATAL ERROR [rtsetparams]:  AudioDevice: Cannot open audio output
device: No such file or directory
*** FATAL ERROR [rtsetparams]:  Failed to create audio device.
*** FATAL ERROR [rtsetparams]:  AudioDevice: This format conversion is
currently not supported!


The first one means your ALSA system is not set up correctly on your
computer, and that's outside of my expertise.

The second one is odd, and indicates we need to add some more error
reporting to figure out where things went wrong.

The third is what happens when you try to use "hw:0" rather than
"plughw:0" as your device.


Sorry I can't help more!


-Doug

**Comment by ggorlen** [comment]
No problem, and thanks so much for all the help! I really appreciate it. I'll post a follow-up if I can get a fix working at some point.

**Comment by dougscott** [comment]
Greg, I am revisiting all these old RTcmix issues - was this problem eventually resolved for you, if if so, could you leave a note as to how?
Thanks!
Doug

**Comment by ggorlen** [comment]
Thanks for the check-in! No, I eventually abandoned the installation and never got it working. You may close the issue if you'd like. I may revisit it at some point in the future when time permits.

**Comment by dougscott** [comment]
OK, sorry to hear!  Next time, we can work together online to get you up and running.
-Doug
