### ISSUE TITLE
Build failing on osx 10.15

### ISSUE THREAD

**Issue by gfarge** [RTcmix/RTcmix#20]
Hi ! 

When compiling RTcmix on osx Catalina (10.15.4), using Xcode 11.4 I am getting the following error:

```
Build settings from command line:
    ARCHS = x86_64
    MACOSX_DEPLOYMENT_TARGET = 10.15.4
    SDKROOT = macosx10.15.4

--- xcodebuild: WARNING: Configuration Deployment is not in the project. Building default configuration.

note: Using new build system
note: Planning build
note: Constructing build description
error: unable to find sdk 'macosx10.15.4' (in target 'MouseWindow' from project 'MouseWindow')

** BUILD FAILED **

make[3]: *** [MouseWindow] Error 65
make[2]: *** [mouse] Error 2
make[1]: *** [control] Error 2
make: *** [src] Error 2
```
I have tried replacing the deployment target in MouseWindow.xcodeproj to "10.15" as advised in a previous issue, but the error persists (I am really ignorant of Xcode, it might have been a really poor try). Do you have any advice on how to fix or work around it?

Many thanks!

Gaspard

**Comment by jwpritchett** [comment]
I'm having exactly the same problem. Tried the same fix with the same lack of success.

Sounds like just a configuration change would fix it. If we're only running this in command line mode, do we even need this component? If not, then an alternative solution is to just comment it out.

Thanks!

James Pritchett (trying to get this to work on Frances White's spiffy new MacBook Pro)

**Comment by johgibso** [comment]
Hi Jamie!

Yes, just comment it out for now. It's just mad about the specific version of the Apple SDK, which doesn't matter for these two ancient little apps. They are not really standalone GUIs, but rather single-window apps that get launched by RTcmix in response to certain script calls, which either display data streams or accept mouse input. Very primitive. Can definitely get by without them.

Best,
John Gibson

**Comment by johgibso** [comment]
I should've said that the easiest way to work around this problem is to edit rtcmix/src/control/Makefile like so, replacing...

DIRS = common midi mouse display datafile pfbus

with 

DIRS = common midi datafile pfbus


John

**Comment by jwpritchett** [comment]
Hi John!

Thanks so much for the solution, especially the specifics on where that bit
is referenced in the make scripts. That saved me a half an hour of running
it down. Changing that line solved the problem and all compiled and
installed fine. Now to hand off to Frances for testing!

Best wishes,

Jamey

**Comment by johgibso** [comment]
Great!

There are lots of fun new Minc features since the old days, courtesy of Doug Scott: using include files, functions, a new map data type (like dictionaries in some languages), ability to hand certain RTcmix functions a native Minc array as their argument list, etc. Some of these are documented here: http://rtcmix.org/reference/scorefile/Minc.php <http://rtcmix.org/reference/scorefile/Minc.php>

(Sorry for spelling your name wrong!)

John

**Comment by gfarge** [comment]
Leaving "mouse" and "display" out the DIRS line of the Makefile worked for me too, it compiled and installed neatly after that.

I'm sad to see the mouse GUI go, though, I liked using it as a way to explore parameters when testing an instrument :^)

Thanks for your answers!

**Comment by dougscott** [comment]
Don't give up on the GUI - I build it under Catalina.  There are probably
just some tweaks to the settings needed.

**Comment by dougscott** [comment]
Here is how to build the GUI apps.  For example, to build MouseWindow:

cd src/control/mouse

make MACOSX_DEPLOYMENT_TARGET=10.9 SDKROOT=


That will build under Catalina
