### ISSUE TITLE
Linux failed compile, string.h include missing from a few files

### ISSUE THREAD

**Issue by mberkowski** [RTcmix/RTcmix#21]
Compiling with GCC 9.2.1 on Ubuntu 19.10, I found I need to add a `#include "string.h"` to

- `src/parser/minc/MincValue.cpp`
- `src/parser/minc/Scope.cpp`

```
MincValue.cpp: In member function ‘bool MincValue::operator==(const MincValue&)’:
MincValue.cpp:351:20: error: ‘strcmp’ was not declared in this scope
  351 |             return strcmp(_u.string, rhs._u.string) == 0;
      |                    ^~~~~~
MincValue.cpp:13:1: note: ‘strcmp’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   12 | #include "Symbol.h"
  +++ |+#include <cstring>
   13 | 
make[3]: *** [<builtin>: MincValue.o] Error 1
```

Configured with only alsa support `./configure --with-alsa`. It compiles cleanly with the added `#include`.

**Comment by dougscott** [comment]
It does not fail to compile for MacOS/iOS, which implies that the #includes
are getting handled differently.  I dont quite understand what you pasted
here:  Is it string.h that should be included, you think, or cstring.h?

Online Linux man page says:

       *#include <string.h>*

       *int strcmp(const char ***s1**, const char ***s2**);*

       *int strncmp(const char ***s1**, const char ***s2**, size_t **n**);*

**Comment by mberkowski** [comment]
@dougscott gcc/g++ error output suggests including `<cstring>` and that does compile working software, but `<string.h>` as you have elsewhere in the project source also works. 

So I can successfully compile by adding either of
```
#include <string.h>
// or
#include <cstring>
```

It has been too many years away from c++ for me know if one is more correct. I see the same result and suitable fix on gcc 7.5.0/ubuntu-18.04 and gcc 9.2.1/ubuntu-19.10, but I believe it will be fine to include `#include <string.h>` the way it is in other project .cpp files. 

Thanks!

**Comment by dougscott** [comment]
OK, pushed those changes.  string.h is always the one to chose of the two.

-Doug

**Comment by mberkowski** [comment]
It compiles, thanks for addressing it!
