### ISSUE TITLE
Build assumes alsa headers are available, even with --without-alsa (the default)

### ISSUE THREAD

**Issue by michaelkarlcoleman** [RTcmix/RTcmix#25]
While trying to build on RHEL 7 server (no sound stuff, etc.), the build fails as `./src/control/midi/portmidi/pm_linux/pmlinuxalsa.c` assumes the presence of 'alsa' headers, even if alsa is not requested.

As a workaround, I removed the contents with `#if 0`, which seemed to lead to a compile and link.  (I haven't been able to test for other reasons.)

**Comment by michaelkarlcoleman** [comment]
FWIW, it appears that the `#if 0` trick doesn't really work.  The problem is that even if one uses a score that explicitly writes to an output file (i.e., a WAV file), the code apparently insists on creating an audio device first and then deleting it, which fails if none are compiled in.

**Comment by dougscott** [comment]
Michael, what happens if you call set_option("audio_off") prior to calling rtsetparams()?

**Comment by michaelkarlcoleman** [comment]
Apologies, I've moved on and no longer have access to the platform.  You can probably just close this.  Thanks!

**Comment by dougscott** [comment]
I verified that calling set_option("audio_off") allows RTcmix to work even if there is no audio device available.
