### ISSUE TITLE
Cannot set rate to 44100 (got 48000) when trying to play a .sco file

### ISSUE THREAD

**Issue by teposamatl** [RTcmix/RTcmix#27]
Hi!

I have installed RTcmix-4.3.2 on Ubuntu 20.04. Installation went smoothly per instruction in INSTALL file. 

I installed prereqs:

	**sudo apt install build-essential
	sudo apt install flex
	sudo apt install bison
	sudo apt install pmidi
	sudo apt install alsa
	sudo apt install libasound2-dev**

Then:

**./configure --with-alsa
make
 make install**

After completing these steps, I created the **.rtcmixrc** file in home directory and included:
**device = 'plughw'**

CMIX starts fine from the command line. However, attempting to play one of the example files in ../docs/sample_scores produces the following error:

**FATAL ERROR [rtsetparams]:  AudioDevice: Cannot set rate to 44100 (got 48000)**

I attempted to change the default sampling rate to 44100 in  **/usr/share/alsa/alsa.conf** to no avail.

I was wondering if anyone has come across a similar problem.

Thanks!

**Comment by johgibso** [comment]
Hi,

Is your config file called ".rtcmixrc" or ".rtcmixrt"? Should be the former.

If your system (or audio interface) is set to 48000 now, maybe try a score that uses that sampling rate. You can modify any of them to play at a different rate. (The ones that read sound files will not work as well.) Try docs/sample_scores/WAVETABLE3.sco, changing the sampling rate in the rtsetparams call.

John

**Comment by teposamatl** [comment]
Hi John,

Thanks for the quick reply! 

**Is your config file called ".rtcmixrc" or ".rtcmixrt"? Should be the former.**

Ooops, typo here! Yes; set to .rtcmixrc.


**If your system (or audio interface) is set to 48000 now, maybe try a score that uses that sampling rate. You can modify any of them to play at a different rate. (The ones that read sound files will not work as well.) Try docs/sample_scores/WAVETABLE3.sco, changing the sampling rate in the rtsetparams call.**

Changing the sampling rate to 48000 at least got sound coming out the speakers! However, it was mostly static sounding. I am not sure if that should be the case. For other files (e.g. CLAR1.sco), I get another error saying:

***** FATAL ERROR [rtsetparams]:  AudioDevice: Cannot set channel count: Invalid argument**

Changing to channel 2 in rtsetparams call, produces sound when calling CMIX < CLAR1.sco, but again static.

I was wondering if you have any other suggestions.

Thanks again!

Josh

**Comment by johgibso** [comment]
Hmm. That doesn't sound good. :)

Can you play a sound file with the aplay command-line program that comes with Alsa and have it sound okay?

I'm operating off of 20-year-old Linux knowledge, by the way. Most of us are Mac-based now.

It might be worth experimenting with some different buffer sizes...

rtsetparams(48000, 2, 1024)

where the third object is a buffer size, most likely a power of two. Try 128, 256, 512, 1024, 2048 to see if the behavior changes.


John

**Comment by dougscott** [comment]
Not sure what "mostly static sounding" means.  What do you hear when you
play this?

rtsetparams(48000, 1, 512);

load("WAVETABLE");

makegen(1, 7, 1000, 0, 50, 1, 900, 1, 50, 0);

makegen(2, 10, 1000, 1)


start = 0.0

freq = 440.0


WAVETABLE(0, 4, 32767, freq);



-Doug

**Comment by dougscott** [comment]
Josh, is this still an open issue?  I now have an updated Fedora machine available for testing such issues.  Please let me know.

**Comment by dougscott** [comment]
I am unable to reproduce anything like this on my Linux machine.  I tried setting the HW to 48000 prior to running the 44.1K score, but it sucessfully reset the SR and played it OK.  Please re-open if the problem persists, and provide a complete set of steps for how you reproduced it.  Also include an output file generated by turning on file-output using rtoutput().

**Comment by dougscott** [comment]
I am unable to reproduce anything like this on my Linux machine. I tried setting the HW to 48000 prior to running the 44.1K score, but it sucessfully reset the SR and played it OK. Please re-open if the problem persists, and provide a complete set of steps for how you reproduced it. Also include an output file generated by turning on file-output using rtoutput().
