### ISSUE TITLE
does not compile on ubuntu 14.04

### ISSUE THREAD

**Issue by revast** [RTcmix/RTcmix#7]
make in the conf folder fails, 
obj not declared in the scope
what I have found out, bison seems to be too new

**Comment by johgibso** [comment]
Hello revast,

First, I'm sorry it has taken so long for you to get a response. We generally toss around issues on our mailing list (http://music.columbia.edu/mailman/listinfo/rtcmix-discuss). We're pretty new to github, so we tend to miss comments people make here. Anyway, I wanted to report that we have support for bison 3 in one of our test branches, so it is coming soon. Thanks for your report.

**Comment by polyrhythmatic** [comment]
@johgibso hi! I'm trying to build rtcmix on ubuntu 14.04.5 LTS and cannot get it to work. Should I be trying the "bison3" branch instead? Not sure what is failing but I have tried everything. I am using it for non real-time rendering.

**Comment by johgibso** [comment]
The bison3 branch is already merged into the main branch. We need to look at what gets printed during make. Please do this...

make uninstall
make distclean
# clear your console now and capture the rest of the printout
./configure
make
make install

JG

**Comment by polyrhythmatic** [comment]
Sorry, should have posted the output originally.

Here is the output for ./configure, make, and make install

[configure_output.txt](https://github.com/RTcmix/RTcmix/files/595021/configure_output.txt)
[make_install_output.txt](https://github.com/RTcmix/RTcmix/files/595023/make_install_output.txt)
[make_output.txt](https://github.com/RTcmix/RTcmix/files/595022/make_output.txt)

**Comment by dougscott** [comment]
I see the first culprit:

make[3]: Entering directory `/usr/local/src/RTcmix/src/audio'
g++ -Wno-deprecated  -I. -I/usr/local/src/RTcmix/include  -I../sndlib
-I../rtcmix -I/usr/local/src/RTcmix/include -O2 -Wall -Wno-unused -fPIC
-DLINUX -m64  -DSTANDALONE  -DTEST_AUDIO_DEVICE -D -c AudioDevice.cpp -o
AudioDevice.o
<command-line>:0:1: error: macro names must be identifiers

This is due to a problem with the config for Linux that we have not worked
out yet.  Add this to your top level site.conf:

AUDIODRIVER=ALSA

For the second culprit, I checked in a fix into src/parser/minc/minc.y

Pull that file (you don't need to update any of the rest of your project),
add the above line, and try again, please.

Doug

**Comment by polyrhythmatic** [comment]
This got me futher - make and make install both complete but for some reason RTcmix/bin is not a directory...

Thanks for the help so far

[configure_output.txt](https://github.com/RTcmix/RTcmix/files/595258/configure_output.txt)
[make_install_output.txt](https://github.com/RTcmix/RTcmix/files/595259/make_install_output.txt)
[make_output.txt](https://github.com/RTcmix/RTcmix/files/595260/make_output.txt)

**Comment by polyrhythmatic** [comment]
output from running `./bin`

```bash
seth@server:/usr/local/src/RTcmix$ ./bin
  Two kinds of sampling rate conversion:
     (1) using Kaiser-windowed low-pass filter (better)
     (2) using linear interpolation only, no filter (faster)
  For (1), use either no option, in which case you get the default,
  decent-quality resampling filter; use the -a option for a better
  quality filter; or use a combination of the -f, -b and -l options
  to design your own filter. (Read "resample.doc" to find out how.)
  For (2), use -i.

  Usage: resample -r NEW_SRATE [options] inputfile [outputfile]

  Options:
     -a       triple-A quality resampling filter
  OR:
     -f NUM   rolloff Frequency (0 < freq <= 1)       [default: 0.9]
     -b NUM   Beta ( >= 1)                            [default: 9.0]
     -l NUM   filter Length (odd number <= 65)        [default: 65]

     -n       No interpolation of filter coefficients (faster)
     -i       resample by linear Interpolation, not with filter
     -t       Terse (don't print out so much)
     -v       print Version of program and quit
  If no output file specified, writes to "inputfile.resamp".
```

**Comment by dougscott** [comment]
Always look at the complete text output from any RTcmix make -- because we
continue past errors (historically, though I am not sure why), a failure
partway through will cause the final stages to fail in odd ways.  That's
the case here in your make_install_output.txt.

I see more compile problems relating to the fact you are building for
Linux.  You must be a rare bird (still working on Linux) given that no-one
else has reported these -- or you have an ancient crufty old compiler
installed.  ;)

I'll make more fixes.

-Doug

**Comment by dougscott** [comment]
Please pull src/parser/minc/args.cpp from Github, remove $(TOP)/bin, and do
a separate "make" (saving its output) and check for errors in that output
before going onto the "make install".  This makes it easier to work through
your issues.

thanks

-Doug

**Comment by polyrhythmatic** [comment]
@dougscott unfortunately I need to render on a server for a web app and RTcmix is much nicer to work with than csound :)

I'm willing to upgrade the compiler, just not sure where to begin. Likely has to do with the fact that I am far from a C++ dev.

**Comment by polyrhythmatic** [comment]
Here is the make output

[make_output.txt](https://github.com/RTcmix/RTcmix/files/595378/make_output.txt)

**Comment by dougscott** [comment]
OK, everything compiled!  Now, before you do your "make install", just type:

make print-DESTDIR

and tell me what that says

**Comment by dougscott** [comment]
No problem -- our goal is to keep this code compatible with older compilers
----- for now.  ;)

-Doug

**Comment by polyrhythmatic** [comment]
@dougscott DESTDIR is /usr/local/src/RTcmix/bin

shall I install it now?

**Comment by dougscott** [comment]
Go for it.

-Doug

**Comment by polyrhythmatic** [comment]
All good to go 👍 

Thanks for the help!

**Comment by EricThomps** [comment]
Hey, I'm on ubuntu 16.04 LTS, and I'm also having some trouble compiling.
[configure_output.txt](https://github.com/RTcmix/RTcmix/files/629552/configure_output.txt)
[make_output.txt](https://github.com/RTcmix/RTcmix/files/629553/make_output.txt)
[make_install_output.txt](https://github.com/RTcmix/RTcmix/files/629554/make_install_output.txt)

**Comment by jwmatthys** [comment]
I think the only significant error is the missing dependencies for PYMIX.

sudo apt-get install libssl-dev

Joel

**Comment by EricThomps** [comment]
Thank you so much!  That was all I needed.

**Comment by revast** [comment]
still having problems. fresh from trunk. Ubuntu 16.04, gcc version 5.4.0 20160609

./configure --with-alsa --with-jack --with-fftw --with-64bit --with-x --with-netplay --with-multithread=4

somehow it tries to build maxmsp stuff?
I temporarily removed

RTcmix/src/maxmsp

as well as 
ifeq ($(BUILDTYPE), MAXMSP)
DIRS += maxmsp
endif

in the makefile to move on



make[2]: Entering directory '/compiles/RTcmix/src/audio'
g++ -Wno-deprecated  -I. -I/compiles/RTcmix/include  -I../sndlib -I../rtcmix -I/compiles/RTcmix/include -O2 -Wall -Wno-unused -fPIC -DLINUX -m64  -DSTANDALONE  -DTEST_AUDIO_DEVICE  -D -c AudioDevice.cpp -o AudioDevice.o
<command-line>:0:1: error: macro names must be identifiers
Makefile:61: recipe for target 'AudioDevice.o' failed
make[2]: *** [AudioDevice.o] Error 1

found in the net:
"You have a -D flag with no name. Look in your makefile to see what is causing it. "

so added 
AUDIO_DEFINES = -DALSA -DJACK

to makefile directly

next one:

make[3]: Entering directory '/compiles/RTcmix/src/parser/minc'
g++ -Wno-deprecated  -I. -I/compiles/RTcmix/include  -I../../include -I../../rtcmix -O2 -Wall -Wno-unused -fPIC -DLINUX -m64  -DSTANDALONE -DEMBEDDED    -c -o minc.o minc.cpp
minc.y:40:0: warning: "YYDEBUG" redefined
 #define YYDEBUG 1
 ^
In file included from minc.l:10:0,
                 from minc.y:12:
minc.hpp:37:0: note: this is the location of the previous definition
 # define YYDEBUG 0
 ^
minc.y:505:2: warning: #warning DAS Make sure yylex_destroy() works [-Wcpp]
 #warning DAS Make sure yylex_destroy() works
  ^
In file included from minc.y:12:0:
lex.yy.c: In function ‘int mm_yy_get_next_buffer()’:
minc.l:41:80: error: cannot convert ‘int*’ to ‘yy_size_t* {aka long unsigned int*}’ for argument ‘2’ to ‘int readFromGlobalBuffer(char*, yy_size_t*, int)’
 #define YY_INPUT(buf,bytes,maxbytes) readFromGlobalBuffer(buf,&(bytes),maxbytes)
                                                                                ^
lex.yy.c:1504:3: note: in expansion of macro ‘YY_INPUT’
   YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
   ^
In file included from minc.y:12:0:
lex.yy.c:1529:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
                                            ^
<builtin>: recipe for target 'minc.o' failed


temporalily removed 
#define YY_INPUT(buf,bytes,maxbytes) readFromGlobalBuffer(buf,&(bytes),maxbytes)



then:

Entering directory '/compiles/RTcmix/src/rtcmix'
g++ -Wno-deprecated  -I. -I/compiles/RTcmix/include  -I/compiles/RTcmix/include -I../include -I../audio -I../sndlib -I./heap -I../conf -O2 -Wall -Wno-unused -fPIC -DLINUX -m64  -DSTANDALONE   -DRT_THREAD_COUNT=4    -c -o rtsetoutput.o rtsetoutput.cpp
rtsetoutput.cpp: In static member function ‘static int Instrument::rtsetoutput(float, float, Instrument*)’:
rtsetoutput.cpp:39:22: error: ‘INT_MAX’ was not declared in this scope
   theInst->_nsamps = INT_MAX;
                      ^
<builtin>: recipe for target 'rtsetoutput.o' failed
make[2]: *** [rtsetoutput.o] Error 1
make[2]: Leaving directory '/compiles/RTcmix/src/rtcmix'
Makefile:13: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/compiles/RTcmix/src'
Makefile:15: recipe for target 'all' failed
make: *** [all] Error 2

I had to add
#define __STDC_LIMIT_MACROS 1
#include <stdint.h>
#include <limits.h>

to the rtsetoutput.cpp to fix this.


still no joy as it fails to link now obviously

**Comment by dougscott** [comment]
Using configure does not set the BUILDTYPE for you - you have to do that by
hand in your site.conf file.  Most of what you get as errors is due to
this, but not all:  You do have to set AUDIODRIVER=ALSA in site.conf as
well (this is a known issue with the configuration).

The errors in the parser code are also due to your BUILDTYPE.

The one other error involving INT_MAX *is* something I need to fix for
Linux (works ok for OS X).

I would revert or store away all your hacks, take care of the BUILDTYPE and
AUDIODRIVER, and try again fresh to see what errors remain for you.  It
will make it easier for me to make changes to help you.

-Doug

**Comment by revast** [comment]
very interesting. I may have overred this.

right, even if I add these things in site.conf like this:

`# site.conf
#
# Definitions in this file override the ones in defs.conf, which are generated
# by the configure script.  Normally, if you're just building the standalone
# RTcmix for Linux or Mac OS X, you should not need to edit this file.
# Just run the configure script.  (See INSTALL for details.)
#
# If you want to build an RTcmix library for embedding in a Max or Pd external,
# or in an iOS or OpenFrameworks app, set the appropriate platform below.

#==============================================================
# Determine target platform

# Choose whether to build standalone RTcmix or embeddable versions for Max,
# Pd, iOS, OpenFrameworks, etc.  See "README.embed" for more information.
BUILDTYPE = STANDALONE
#BUILDTYPE = OSXEMBEDDED
#BUILDTYPE = MAXMSP
#BUILDTYPE = PD
#BUILDTYPE = IOS

# Overrides (please make sure you know what you are doing)

# For OSXEMBEDDED, you can override the default RTLIBTYPE (DYNAMIC) to build a static
# version of the rtcmix library by uncommenting this.  This will not affect
# STANDALONE, MAXMSP, or IOS builds.

#RTLIBTYPE = STATIC

# For IOS, you can override the default AUDIODRIVER (APPLE) to build a version of RTcmix
# which uses the embedded audio device to let you call the RTcmix rendering callback
# directly in your environment.  The default APPLE device plays and records audio
# internal to RTcmix.  This will not affect STANDALONE, MAXMSP, or PD builds.

#AUDIODRIVER = EMBEDDEDAUDIO

# End of Overrides

# If selecting "IOS", then one of the IPHONE_TYPEs has to be uncommented.
#IPHONE_TYPE = SIMULATOR
#IPHONE_TYPE = DEVICE

# If you're building a binary package for OS X or Linux, uncomment this:
#PKG = TRUE

# If you're building MAX, set the version here
#MAX_VERSION = 7
# Leave this set to 6 until we do the v7 SDK port
#MAX_SDK_VERSION = 6


#==============================================================
# Platform-specific settings

# Here we set compilation flags and other settings, such as local
# directories, that apply only to this site's installation. Other
# settings that are unlikely to change belong in makefile.conf.in.

# -- Linux ----------------------------------------------------
ifeq ($(ARCH), LINUX)
  OPT = -O2 -Wall -Wno-unused
  # for use when building binary pkg (currently unimplemented)
  ifeq ($(PKG), TRUE)
    LIBDESTDIR = /usr/local/src/rtcmix/shlib
  endif
endif

# -- Mac OS X -------------------------------------------------
ifeq ($(ARCH), MACOSX)

  # -- standalone ---------------------------------------------
  ifeq ($(BUILDTYPE), STANDALONE)
    OPT = -g3 -O3 -Wall -Wno-unused
    # for use when building binary pkg
    ifeq ($(PKG), TRUE)
      LIBDESTDIR = /Applications/rtcmix/shlib
    endif
  endif

  # -- MaxMSP -------------------------------------------------
  ifeq ($(BUILDTYPE), MAXMSP)
    OPT = -g3 -O3 -Wall -Wno-unused
	 ifeq ($(MAX_SDK_VERSION), 7)
	 	 ARCH_BITFLAGS = -m64
	 else
	 	 ARCH_BITFLAGS = -m32
	 endif
     ifeq ($(MAX_VERSION), 6)
		 # The dir that will contain rtcmix~.mxo
	     MAX_INSTALL_DIR = "/Applications/Max 6.1/Cycling '74/msp-externals/RTcmix/"
		 # The dir that will contain the dynamic shared library for the Max object
	     MAX_LIB_INSTALL_DIR = "/Applications/Max 6.1/Cycling '74/msp-externals/RTcmix/rtcmix-dylibs/"
	 endif
	 ifeq ($(MAX_VERSION), 7)
		 # The dir that will contain rtcmix~.mxo
	     MAX_INSTALL_DIR = "/Users/Shared/Max 7/Library/RTcmix/"
		 # The dir that will contain the dynamic shared library for the Max object
	     MAX_LIB_INSTALL_DIR = "/Users/Shared/Max 7/Library/RTcmix/rtcmix-dylibs/"
	 endif
		 # The following must be set the path to your Max SDK
		 MAX_SDK_PATH = /Users/brad/software/maxstuff/MaxSDK-5.1.6
		 # Don't touch this unless the SDK layout changes.
	     MAX_INCLUDES = -I${MAX_SDK_PATH}/c74support/max-includes \
		 -I${MAX_SDK_PATH}/c74support/msp-includes \
		 -F${MAX_SDK_PATH}/c74support/max-includes \
		 -F${MAX_SDK_PATH}/c74support/msp-includes \
		 -I/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers

		 # This determines if MAX uses the old MOVE and PLACE or the new DMOVE, MMOVE, and MPLACE
		 # FALSE by default because sample scores, etc., use old commands.
		 EMBEDDED_USE_MMOVE=FALSE
  endif

  # -- Pd -----------------------------------------------------
  ifeq ($(BUILDTYPE), PD)
    OPT = -g3 -O3 -Wall -Wno-unused
  endif

  # -- iOS ----------------------------------------------------
  ifeq ($(BUILDTYPE), IOS)
    ifeq ($(IPHONE_TYPE), SIMULATOR)
      OPT = -g -Wall -Wno-unused
    endif
    ifeq ($(IPHONE_TYPE), DEVICE)
      OPT = -g3 -O3 -Wall -Wno-unused
    endif
  endif

endif

# -- FreeBSD --------------------------------------------------
ifeq ($(ARCH), FREEBSD)
  OPT = -O2 -Wall -Wno-unused
endif

# -- SGI ------------------------------------------------------
ifeq ($(ARCH), SGI)
  OPT = -O2 -Wall -Wno-unused
endif

# Uncomment this only if you wish to create a version of the RTcmix
# library which supports more than 8 audio channels.
# MAXCHANS = 8

#==============================================================
# Parsers

# NB: Most of this overrides the results of the configure script.

ifeq ($(BUILDTYPE), STANDALONE)
# Uncomment this to enable use of the Perl front end to RTcmix.
# This requires a perl version >= 5.005_62.
PERL_SUPPORT = TRUE
# Say which perl to use: just "perl" if you only have one; otherwise,
# give full path name of perl to use, e.g., /usr/local/bin/perl.
PERL = /usr/bin/perl
# Set this to FALSE if your perl libraries are NOT in /usr/local/lib,
# but rather are installed in /usr/lib.
#PERL_IN_LOCAL = FALSE

# Uncomment this to enable use of the Python front end to RTcmix.
PYTHON_SUPPORT = TRUE
# Say which python to use: just "python" if you only have one; otherwise,
# give full path name of python to use, e.g., /usr/local/bin/python.
PYTHON = python
# We use a python extension to make RTcmix commands accessible inside
# python.  The default is to link this extension statically.  If you
# would like (or need) to link it dynamically, set this to FALSE.
# Then go into src/parser/python and "make install" as root.  That
# will copy the extension into your system-wide site-packages dir,
# where PYMIX will be able to find it at run time.
PYTHON_EXT_STATIC_LINK = TRUE

AUDIODRIVER=ALSA
#USE_OSX_DISPATCH = TRUE
endif
`
I still had to add --with-python and --with-perl  to ./configure , which is undocumented. I am quite astonished that max is the default config, but so it shall be.
maybe a site.conf.linux file would be more user friendly. 

So when I add AUDIODRIVER=ALSA , will it still work with Jack as well?


I am now getting 

`make[3]: Entering directory '/media/hero/vault/compiles/RTcmix2/RTcmix/insts/std/LOOP'
g++ -Wno-deprecated  -I. -I/media/hero/vault/compiles/RTcmix2/RTcmix/include  -O2 -Wall -Wno-unused -fPIC -DLINUX -m64  -DSTANDALONE -DNETAUDIO -DJACK -DFFTW -DMULTI_THREAD -I. -Wall    -c -o LOOP.o LOOP.cpp
In file included from /media/hero/vault/compiles/RTcmix2/RTcmix/include/ugens.h:12:0,
                 from LOOP.cpp:21:
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:74:5: error: ‘atomic_t’ does not name a type
     atomic_t val;
     ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h: In constructor ‘AtomicInt::AtomicInt(int)’:
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:76:42: error: ‘val’ was not declared in this scope
     AtomicInt(int inVal=0) { atomic_set(&val, inVal); }
                                          ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:76:52: error: ‘atomic_set’ was not declared in this scope
     AtomicInt(int inVal=0) { atomic_set(&val, inVal); }
                                                    ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h: In member function ‘AtomicInt::operator int() const’:
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:77:49: error: ‘val’ was not declared in this scope
     operator int () const { return atomic_read(&val); }
                                                 ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:77:52: error: ‘atomic_read’ was not declared in this scope
     operator int () const { return atomic_read(&val); }
                                                    ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h: In member function ‘void AtomicInt::increment()’:
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:78:36: error: ‘val’ was not declared in this scope
     void increment() { atomic_inc(&val); }
                                    ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:78:39: error: ‘atomic_inc’ was not declared in this scope
     void increment() { atomic_inc(&val); }
                                       ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h: In member function ‘bool AtomicInt::incrementAndTest()’:
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:79:59: error: ‘val’ was not declared in this scope
     bool incrementAndTest() { return atomic_inc_and_test(&val); }
                                                           ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:79:62: error: ‘atomic_inc_and_test’ was not declared in this scope
     bool incrementAndTest() { return atomic_inc_and_test(&val); }
                                                              ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h: In member function ‘bool AtomicInt::decrementAndTest()’:
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:80:59: error: ‘val’ was not declared in this scope
     bool decrementAndTest() { return atomic_dec_and_test(&val); }
                                                           ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:80:62: error: ‘atomic_dec_and_test’ was not declared in this scope
     bool decrementAndTest() { return atomic_dec_and_test(&val); }
                                                              ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h: In member function ‘int AtomicInt::operator=(int)’:
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:81:44: error: ‘val’ was not declared in this scope
     int operator = (int rhs) { atomic_set(&val, rhs); return atomic_read(&val); }
                                            ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:81:52: error: ‘atomic_set’ was not declared in this scope
     int operator = (int rhs) { atomic_set(&val, rhs); return atomic_read(&val); }
                                                    ^
/media/hero/vault/compiles/RTcmix2/RTcmix/include/rt_types.h:81:78: error: ‘atomic_read’ was not declared in this scope
     int operator = (int rhs) { atomic_set(&val, rhs); return atomic_read(&val); }
                                                                              ^
<builtin>: recipe for target 'LOOP.o' failed
make[3]: *** [LOOP.o] Error 1
`

**Comment by dougscott** [comment]
Sorry - your reply is unreadable on an iPhone 😊. I may be mistaken about having to set BUILDTYPE by hand, but your configure args did not specify either Linux or standalone and it is clear from your compile errors that it was trying to compile an "embedded" configuration. I'll read through your reply later today. 

Any others want to comment on the configure?


Doug

**Comment by dougscott** [comment]
Fixing one thing at a time.  You should not have MULTI_THREAD_SUPPORT set
for Linux. It pulls in stuff which is OS X-specific.

Yes, I should add a line that causes a config failure if you try this. ;)

I'll check email again in a few hours.

-Doug

**Comment by revast** [comment]
well then...

only one error left (wow!)

```
In file included from minc.y:12:0:
lex.yy.c: In function ‘int yy_get_next_buffer()’:
lex.yy.c:1529:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
                                            ^
minc.y: In function ‘int yyparse()’:
minc.y:318:32: error: assignment of read-only location ‘* strrchr(vcopy, 34)’
           *strrchr(vcopy, '"') = '\0';
                                ^
```


full:
```
make[4]: Entering directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/parser/minc'
g++ -Wno-deprecated  -I. -I/media/hero/vault/compiles/RTcmix2/RTcmix/include  -I../../include -I../../rtcmix -g3 -O3 -Wall -Wno-unused -fPIC -DLINUX -m64  -DSTANDALONE -DNETAUDIO -DJACK -DFFTW   -c -o minc.o minc.cpp
minc.y:40:0: warning: "YYDEBUG" redefined
 #define YYDEBUG 1
 ^
In file included from minc.l:10:0,
                 from minc.y:12:
minc.hpp:37:0: note: this is the location of the previous definition
 # define YYDEBUG 0
 ^
In file included from minc.y:12:0:
lex.yy.c: In function ‘int yy_get_next_buffer()’:
lex.yy.c:1529:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
                                            ^
minc.y: In function ‘int yyparse()’:
minc.y:318:32: error: assignment of read-only location ‘* strrchr(vcopy, 34)’
           *strrchr(vcopy, '"') = '\0';
                                ^
<builtin>: recipe for target 'minc.o' failed
make[4]: *** [minc.o] Error 1
make[4]: Leaving directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/parser/minc'
make[4]: Entering directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/parser/perl'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/parser/perl'
make[4]: Entering directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/parser/python'
python setup.py build
running build
running build_ext
rm -f rtcmixmodule.o
ln -s "`find . -name rtcmixmodule.o`" .
make[4]: Leaving directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/parser/python'
make[3]: Leaving directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/parser'
g++ -Wno-deprecated -shared -Wl,-soname,librtcmix.so -m64  -o librtcmix.so addcheckfunc.o addrtInst.o buffers.o bus_config.o checkInsts.o dispatch.o filter.o Instrument.o intraverse.o loader.o lfo.o minc_info.o minc_functions.o DataFile.o MMPrint.o Option.o PFBusData.o PField.o PFieldSet.o Random.o RawDataFile.o RefCounted.o RTcmix.o InputFile.o rtcmix_types.o rtcmix_wrappers.o rtgetin.o rtgetsamps.o rtinput.o rtoutput.o rtsendsamps.o rtsetinput.o rtsetoutput.o rtsetparams.o rtwritesamps.o set_option.o sound_sample_buf_read.o table.o tableutils.o modtable.o ops.o utils.o rt_ug_intro.o connection.o converter.o monitor.o setnetplay.o check_byte_order.o command_line.o funderflow.o getsample.o infile.o io.o load_utils.o merror.o message.o minout.o m_system.o printsf.o profile.o resetamp.o sampfunc.o sfcopy.o sfprint.o sfstats.o sound.o soundio.o tempo.o ug_intro.o gen/fdump.o gen/floc.o gen/fnscl.o gen/fplot.o gen/fsize.o gen/gen10.o gen/gen17.o gen/gen18.o gen/gen1.o gen/gen20.o gen/gen24.o gen/gen25.o gen/gen2.o gen/gen3.o gen/gen4.o gen/gen5.o gen/gen6.o gen/gen7.o gen/gen9.o gen/makegen.o gen/modgens.o heap/heap.o heap/queue.o heap/rtQueue.o ../../insts/base/MIX/MIX.o ../audio/audio_devices.o   ../audio/librtaudio.a -lfftw3f -ljack ../sndlib/sndlib.a ../conf/libconf.a ../parser/minc/libminc.a ../../genlib/libgen.a -Wl,-rpath /media/hero/vault/compiles/RTcmix2/RTcmix/lib -L/media/hero/vault/compiles/RTcmix2/RTcmix/lib -lgen -lasound -lpthread -lm -ldl 
g++: error: ../parser/minc/libminc.a: No such file or directory
Makefile:391: recipe for target 'librtcmix.so' failed
make[2]: *** [librtcmix.so] Error 1
make[2]: Leaving directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src/rtcmix'
Makefile:15: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/media/hero/vault/compiles/RTcmix2/RTcmix/src'
make[1]: Entering directory '/media/hero/vault/compiles/RTcmix2/RTcmix/insts'
find: warning: you have specified the -mindepth option after a non-option argument -type, but options are not positional (-mindepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: warning: you have specified the -mindepth option after a non-option argument -type, but options are not positional (-mindepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
```

**Comment by dougscott** [comment]
See if changing the previous line:

const char *vcopy = strsave(value+1);


to:

char *vcopy = strsave(value+1);


fixes it.  If so, let me know and I will fix it on GitHub.

-Doug

**Comment by revast** [comment]
yup. Fixed.

**Comment by revast** [comment]
hmm but --prefix does not work? just installs in the source directory, regardless what I tell it, and creates a file named bin instead of a directory??

**Comment by dougscott** [comment]
Sorry, I did not write (nor do I use) that part of the configuration
system.  It's not that it tries to create a file named bin -- first it
fails to create the directory $(DEST)/bin, then it attempts to install the
file into $(DEST)/bin, which ends up just copying the file to the  $(DEST)
directory as "bin" because there is no directory there.

John, Brad -- we've been handling these issues off-list, but this "creates
a file named bin" issue is one I've heard many times but don't know what
problem it indicates -- can you please field that issue here?

-Doug

**Comment by dougscott** [comment]
Back to your original ALSA issue:  If I recall, you had alsa in your
arguments to configure, right?  What do you have for AUDIODRIVER = in your
defs.conf file?  Trying to figure out why this is not getting set
correctly...

-Doug

**Comment by revast** [comment]
right, I did mkdir bin, and it copied all the binaries into it.

about ALSA,   

AUDIODRIVER = ALSA was what I have put into SITE.conf

I am not shure I have a problem left with ALSA, as compiles through with site.conf

```
#==============================================================
# Determine target platform

BUILDTYPE = STANDALONE
AUDIODRIVER = ALSA
ARCH = LINUX
#==============================================================
# Platform-specific settings

# -- Linux ----------------------------------------------------
ifeq ($(ARCH), LINUX)
  OPT = -O2 -Wall -Wno-unused
endif
 --build=
  # -- standalone ---------------------------------------------
  ifeq ($(BUILDTYPE), STANDALONE)
    OPT = -g3 -O3 -Wall -Wno-unused
  endif

  # -- Pd -----------------------------------------------------
  ifeq ($(BUILDTYPE), PD)
    OPT = -g3 -O3 -Wall -Wno-unused
  endif

# Uncomment this only if you wish to create a version of the RTcmix
# library which supports more than 8 audio channels.
# MAXCHANS = 8

#==============================================================
# Parsers
ifeq ($(BUILDTYPE), STANDALONE)
PERL_SUPPORT = TRUE
PERL = /usr/bin/perl
PERL_IN_LOCAL = FALSE

PYTHON_SUPPORT = TRUE
PYTHON = python
PYTHON_EXT_STATIC_LINK = TRUE
endif
```

about defs.conf, it looks like this:

```
ARCH = LINUX
CC = gcc
CXX = g++
#OPT = -g -O2
PICFLAGS =  -fPIC
ARCH_BITFLAGS = -m64 
BUILD_ARCH = 
MULTI_THREAD_SUPPORT = FALSE
THREAD_COUNT = 2
USE_OSX_DISPATCH = @USE_OSX_DISPATCH@
PERL_SUPPORT = TRUE
PERL = perl
PERL_IN_LOCAL = FALSE
PYTHON_SUPPORT = TRUE
PYTHON = python
NPLAY_SUPPORT = TRUE
JACK_SUPPORT = TRUE
JACK_CFLAGS = 
JACK_LIBS = -ljack
FFTW_SUPPORT = TRUE
FFTW_CFLAGS = 
FFTW_LIBS = -lfftw3f
OSC_SUPPORT = TRUE
LIBLO_CFLAGS = 
LIBLO_LIBS = -llo -lpthread
SDIF_SUPPORT = @SDIF_SUPPORT@
SDIF_CFLAGS = @SDIF_CFLAGS@
SDIF_LIBS = @SDIF_LIBS@

prefix = /opt/RTcmix
exec_prefix = ${prefix}
# suppress warning in configure...
datarootdir = ${prefix}/share
#DESTDIR = ${exec_prefix}/bin
MANDESTDIR = ${datarootdir}/man
HTMLDESTDIR = /media/hero/vault/compiles/RTcmix2/RTcmix/docs/html

XLIBDIR = 

# for debugging configure.ac
#WITH_VAL = @WITH_VAL@
```
